// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKxBoxmQwBlG7ZG7qRyc6HVjEc4RgUIw',
    appId: '1:1068182337772:web:e9fb665f600993e84f8dc9',
    messagingSenderId: '1068182337772',
    projectId: 'fixit-5107c',
    authDomain: 'fixit-5107c.firebaseapp.com',
    storageBucket: 'fixit-5107c.firebasestorage.app',
    measurementId: 'G-S2HTENPS19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBuXKiPLQOU05ocOCifbcrPkeoMd8ONg',
    appId: '1:1068182337772:android:49a46d74ce697aeb4f8dc9',
    messagingSenderId: '1068182337772',
    projectId: 'fixit-5107c',
    storageBucket: 'fixit-5107c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwmTay7pH7683MSZNxSKxcqtS5gHiav0',
    appId: '1:1068182337772:ios:3fcc1900223759964f8dc9',
    messagingSenderId: '1068182337772',
    projectId: 'fixit-5107c',
    storageBucket: 'fixit-5107c.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwmTay7pH7683MSZNxSKxcqtS5gHiav0',
    appId: '1:1068182337772:ios:3fcc1900223759964f8dc9',
    messagingSenderId: '1068182337772',
    projectId: 'fixit-5107c',
    storageBucket: 'fixit-5107c.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKxBoxmQwBlG7ZG7qRyc6HVjEc4RgUIw',
    appId: '1:1068182337772:web:013b26a1d361e2a34f8dc9',
    messagingSenderId: '1068182337772',
    projectId: 'fixit-5107c',
    authDomain: 'fixit-5107c.firebaseapp.com',
    storageBucket: 'fixit-5107c.firebasestorage.app',
    measurementId: 'G-NCBC6DNZR5',
  );
}
